### ISSUE TITLE
Develop Posts & Tags Display with Layout Options

### ISSUE THREAD

**Issue by Valx01P** [web103-group6/web103_team6_final_project#17]
### Issue Title: Develop Posts & Tags Display with Layout Options

---

**Description**  
- A user should be able to see a display of posts and tags on the website, depending on the page of course, and for both we want one way to control their layout, based on the Figma design, develop the display for the tags and posts with a way to change the layout, for now you can just use an html selector with options and have 3 options appear, based on these 3 options you'll change the style of the display to show more or less items, or as a grid or list, for the options, maybe you can have a short list that shows fewer items, but they appear bigger, and a long list that shows more items and is smaller, or a grid with medium items., you could likely do this by changing the class of the list container dynamically based on the state

**Assignee(s)**  
- @mohammadmehrab

**Comment by Valx01P** [comment]
Originally, I had this planned as 3 separate issues,

- Develop Layout & Popout Layout Options
- Develop Posts Display
- Develop Tags Display

But since they are all pretty related it would be more convenient to just work on it all in one branch

**Comment by mohammadmehrab** [comment]
Do you have an example I can work off of? Like something similar on an existing website I can look at; I'm having trouble understanding your description

**Comment by Valx01P** [comment]
The issue was made today, but I was planning on talking about it tomorrow
in class
